### ISSUE TITLE
How to convert your model to .scn format that can be used in ARKit?

### ISSUE THREAD

**Issue by SandroChen** [hinzka/52blendshapes-for-VRoid-face#1]
Just like the title.

**Comment by hinzka** [comment]
It seems that the conversion is possible on Blender.

Use the following two addons.

 - VRM_Addon_for_Blender
	https://github.com/saturday06/VRM_Addon_for_Blender

 - SceneFileExporter
	https://github.com/Dummiesman/SceneFileExporter


1) Import VRM files into Blender  
![2021-12-23_13h43_30](https://user-images.githubusercontent.com/32916633/147189193-2a2b3529-170e-4062-ad74-af6a1debed0e.png)


2) Export the scn file from Blender  
![2021-12-23_13h44_04](https://user-images.githubusercontent.com/32916633/147189201-3bc84a20-79b5-424b-b66b-12b7965ed3df.png)

**Comment by hinzka** [comment]
Load the VRM file into Blender and output a Collada(.dae) file.
Import it into Xcode and convert it to a .scn file.


Reference article (Japanese)
https://qiita.com/shu223/items/0161f82d000d5cdf009c

Use the following add-on.

 - VRM_Addon_for_Blender
	https://github.com/saturday06/VRM_Addon_for_Blender


1) Import the VRM file into Blender

2) Export from Blender as a Collada(.dae) file

3) Import the Collada(.dae) file into the Xcode

4) Execute "Convert Scenekit scene file format(.scn)" from the Edit menu

**Comment by hinzka** [comment]
Caution.
The specification called "Perfect-Sync" uses 52 blendshape clips in the VRM to do face tracking instead of 52 blendshapes.

VRM's Technical Specs  (Assets related to BlendShape)  
https://vrm.dev/en/docs/univrm/blendshape/blendshape_setup/

Some blendshapes (browInnerUp, browDown, mouthSmile, etc.) are set to move excessively large in the VRM file released in this project so that they can be copied to other VRoid models.
Therefore, if this model is converted directly for iOS, the facial expressions will not work correctly.

**Comment by SandroChen** [comment]
Do you mean the only way to use your model in ARKit is through the specification called "Perfect-Sync"?

**Comment by SandroChen** [comment]
I just tried your method and found this method didn't work. 

> Load the VRM file into Blender and output a Collada(.dae) file. Import it into Xcode and convert it to a .scn file.
> 
> Reference article (Japanese) https://qiita.com/shu223/items/0161f82d000d5cdf009c
> 
> Use the following add-on.
> 
> * VRM_Addon_for_Blender
>   https://github.com/saturday06/VRM_Addon_for_Blender
> 
> 1. Import the VRM file into Blender
> 2. Export from Blender as a Collada(.dae) file
> 3. Import the Collada(.dae) file into the Xcode
> 4. Execute "Convert Scenekit scene file format(.scn)" from the Edit menu

**Comment by hinzka** [comment]
> I just tried your method and found this method didn't work.

I'm sorry to hear that.I don't know any more about it.
You are free to convert this VRM to other file formats and use it as you wish, but I cannot support it.

> Do you mean the only way to use your model in ARKit is through the specification called "Perfect-Sync"?

You can compose the data set inside the BlendShapseClip and output it to 52 blendshapes for native ARKit face tracking.
You can do this manually in Blender.

In addition, HANA_Tool, a Unity asset, has a function (ClipToShape) to output 52 blendshapes with expressions adjusted by 52 clips. For more details, please refer to the HANA_Tool specification.
https://kuniyan.booth.pm/items/2604269
