### ISSUE TITLE
Mesh incompatible with VRoid Studio 1.7.0

### ISSUE THREAD

**Issue by TigerHix** [hinzka/52blendshapes-for-VRoid-face#4]
Hi Hinzka,

Thank you for your work on perfect sync! I would like to use the blendshape data in this repo, but they seem outdated for VRoid Studio 1.7.0.

![image](https://user-images.githubusercontent.com/3406505/169895130-b2c35dbf-0ca6-4e2a-a232-139cb7dde9fa.png)

^ The default female model face mesh exported by VRoid Studio 1.7.0 now has 4083 vertices, instead of 4709 vertices in 1.4.2.

My export settings are as below:

![image](https://user-images.githubusercontent.com/3406505/169895236-c2dfae5a-0483-419a-a882-1cce09809123.png)

Wondering if there are something wrong with my export settings, or VRoid Studio indeed updated their base mesh. Thanks!

**Comment by hinzka** [comment]
<img width="556" alt="143596074-e64bd043-ddf4-4c59-a70d-b2684f993401" src="https://user-images.githubusercontent.com/32916633/170205649-d7996773-e2fc-4ae8-8ab5-1da50647fc15.png">
Check the VRM output settings in VRoidStudio.

By default, the setting to remove transparent areas is enabled.
Please uncheck this checkbox before VRM output.
(This image is also available on this Github wiki.)

**Comment by TigerHix** [comment]
Works perfectly now! Thanks a lot :)
