### ISSUE TITLE
How can I import this VRM into VRoid ?

### ISSUE THREAD

**Issue by Morgan-6Freedom** [hinzka/52blendshapes-for-VRoid-face#6]
How can I import this VRM into VRoid ?

**Comment by hinzka** [comment]
You cannot import VRM files into VRoid Studio.

Please create your character in VRoid Studio first, and then export the VRM model.
(When exporting, you need to uncheck the "Delete Transparent Mesh" checkbox.)

By using an external tool such as HANA_Tool or FaceForge,
 you can transfer BlendShapes from this VRM model to your VRM model.
Please refer to the documentation of each tool for details.
