### ISSUE TITLE
Model license?

### ISSUE THREAD

**Issue by Silverlan** [hinzka/52blendshapes-for-VRoid-face#7]
Hello!

I was wondering if I could use these models as reference models for an animation program I'm working on. Would that be allowed, or are there any licensing restrictions?

Thank you.

**Comment by hinzka** [comment]
Hello!
Thank you for your interest.
Whether your work is paid or free, please feel free to use this data. No credit is necessary.
I would be happy to help you in your activities.

**Comment by Silverlan** [comment]
ありがとうございます！That's very generous. 😄
I'm working on integrating [mediapipe](https://github.com/google/mediapipe) into a 3D animation software I'm working on, and it uses the exact same [blend shape conventions](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/vision/face_landmarker/face_landmarker_graph.cc#L213) as these models, so this will come in very handy for me.

Just one question:
I imported the model into Blender using the [VRM addon](https://vrm-addon-for-blender.info/en/), but I can't seem to find the textures for it anywhere. They show up fine in Blender:
![blender_WUHWJ6YnZ2](https://github.com/hinzka/52blendshapes-for-VRoid-face/assets/3609960/fc1c5479-af98-4d01-bd1f-57dd8568e1c2)
However, when I try exporting the model (e.g. in the glTF format) the textures are missing:
![ApplicationFrameHost_4viV7BcHtI](https://github.com/hinzka/52blendshapes-for-VRoid-face/assets/3609960/4515b697-9092-40f0-a85c-f538ed674092)
(The hair is in reverse as well for some reason, but I can fix that.)

Do you know how I can extract them from the vrm files?

**Comment by Silverlan** [comment]
Found a solution:
Apparently the vrm format is already based on glTF and you can just rename the file extension. Got it working now, thanks again 😄!

https://github.com/hinzka/52blendshapes-for-VRoid-face/assets/3609960/0d8a1037-611f-4868-83b4-20c5b7441c5f

**Comment by hinzka** [comment]
Sorry for the delay in responding. Thank you!
